#include "ferrum/renderer/pbr_shader.h"

/* ── Vertex shader ──────────────────────────────────────────────────────
 * Static-mesh attribute layout: 0=pos 1=normal 2=tangent.xyzw 3=uv0 4=uv1.
 * Emits world position, a world-space TBN basis, and both UV sets. */
static const char *const PBR_VS =
    "#version 330 core\n"
    "layout(location=0) in vec3 in_position;\n"
    "layout(location=1) in vec3 in_normal;\n"
    "layout(location=2) in vec4 in_tangent;\n"
    "layout(location=3) in vec2 in_uv0;\n"
    "layout(location=4) in vec2 in_uv1;\n"
    "uniform mat4 u_model;\n"
    "uniform mat4 u_view;\n"
    "uniform mat4 u_projection;\n"
    "out vec3 v_world_pos;\n"
    "out vec3 v_normal;\n"
    "out vec3 v_tangent;\n"
    "out vec3 v_bitangent;\n"
    "out vec2 v_uv0;\n"
    "out vec2 v_uv1;\n"
    "out float v_view_z;\n"
    "void main() {\n"
    "  vec4 wp = u_model * vec4(in_position, 1.0);\n"
    "  v_world_pos = wp.xyz;\n"
    "  v_view_z = (u_view * wp).z;\n"
    "  mat3 nm = mat3(u_model);\n" /* uniform-scale assumption */
    "  v_normal = normalize(nm * in_normal);\n"
    "  v_tangent = normalize(nm * in_tangent.xyz);\n"
    "  v_bitangent = normalize(cross(v_normal, v_tangent) * in_tangent.w);\n"
    "  v_uv0 = in_uv0;\n"
    "  v_uv1 = in_uv1;\n"
    "  gl_Position = u_projection * u_view * wp;\n"
    "}\n";

/* ── Fragment shader ────────────────────────────────────────────────────
 * Metallic-roughness Cook-Torrance: GGX distribution, Smith height-correlated
 * visibility (Schlick-GGX), Schlick Fresnel; tangent-space normal mapping, AO,
 * roughness min/max remap, tint, specular strength, emissive self-shading.
 * Lit by one directional sun + a constant ambient (extended later). */
static const char *const PBR_FS =
    "#version 330 core\n"
    "in vec3 v_world_pos;\n"
    "in vec3 v_normal;\n"
    "in vec3 v_tangent;\n"
    "in vec3 v_bitangent;\n"
    "in vec2 v_uv0;\n"
    "in vec2 v_uv1;\n"
    "in float v_view_z;\n"
    "out vec4 frag;\n"
    "uniform sampler2D u_albedo_map;\n"
    "uniform sampler2D u_normal_map;\n"
    "uniform sampler2D u_metallic_map;\n"
    "uniform sampler2D u_roughness_map;\n"
    "uniform sampler2D u_ao_map;\n"
    "uniform sampler2D u_emissive_map;\n"
    "uniform int u_has_albedo;\n"
    "uniform int u_has_normal;\n"
    "uniform int u_has_metallic;\n"
    "uniform int u_has_roughness;\n"
    "uniform int u_has_ao;\n"
    "uniform int u_has_emissive;\n"
    "uniform vec3 u_tint;\n"
    "uniform vec3 u_emissive_color;\n"
    "uniform float u_specular_strength;\n"
    "uniform float u_metalness;\n"
    "uniform float u_roughness_min;\n"
    "uniform float u_roughness_max;\n"
    "uniform float u_emissive_strength;\n"
    "uniform float u_normal_scale;\n"
    "uniform vec2 u_uv_scale;\n"
    "uniform float u_ao_strength;\n"
    "uniform vec3 u_eye_pos;\n"
    "uniform vec3 u_sun_dir;\n"
    "uniform vec3 u_sun_color;\n"
    "uniform vec3 u_ambient;\n"
    /* Current-pass punctual light set (point/spot/directional). In the clustered\n"
     * pipeline this is the per-cluster subset; here it is uploaded directly. */
    "#define PBR_MAX_LIGHTS 32\n"
    "uniform int u_light_count;\n"
    "uniform int u_light_type[PBR_MAX_LIGHTS];\n"    /* 0=point 1=directional 2=spot */
    "uniform vec3 u_light_pos[PBR_MAX_LIGHTS];\n"    /* world position (point/spot) */
    "uniform vec3 u_light_dir[PBR_MAX_LIGHTS];\n"    /* forward axis (dir/spot) */
    "uniform vec3 u_light_color[PBR_MAX_LIGHTS];\n"  /* colour * intensity */
    "uniform float u_light_range[PBR_MAX_LIGHTS];\n"
    "uniform float u_light_cos_inner[PBR_MAX_LIGHTS];\n"
    "uniform float u_light_cos_outer[PBR_MAX_LIGHTS];\n"
    /* Clustered forward+: per-fragment cluster lookup into GPU light buffers.\n"
     * u_cluster_range: RG32I (offset,count) per cluster; u_light_index: R32I\n"
     * flat index list; u_light_data: RGBA32F, 4 texels/light. */
    "uniform int u_clustered;\n"
    "uniform isamplerBuffer u_cluster_offset;\n"
    "uniform isamplerBuffer u_cluster_count;\n"
    "uniform isamplerBuffer u_light_index;\n"
    "uniform samplerBuffer u_light_data;\n"
    "uniform vec3 u_cluster_dims;\n"     /* tiles_x, tiles_y, slices (as floats) */
    "uniform vec3 u_screen;\n"           /* viewport pixels in .xy */
    "uniform float u_cluster_near;\n"
    "uniform float u_cluster_far;\n"
    /* Baked SH9 lightmap: 9 coefficient maps (RGB = the coeff for R,G,B),\n"
     * sampled by uv1; u_sh_enabled toggles it as the diffuse indirect term. */
    "uniform sampler2D u_sh0;\n"
    "uniform sampler2D u_sh1;\n"
    "uniform sampler2D u_sh2;\n"
    "uniform sampler2D u_sh3;\n"
    "uniform sampler2D u_sh4;\n"
    "uniform sampler2D u_sh5;\n"
    "uniform sampler2D u_sh6;\n"
    "uniform sampler2D u_sh7;\n"
    "uniform sampler2D u_sh8;\n"
    "uniform int u_sh_enabled;\n"
    "uniform float u_sh_scale;\n" /* baked-lightmap intensity multiplier (default 1). */
    /* Debug visualisation: 0=off, 1=raw SH DC term (coeff0) at v_uv1,
     * 2=reconstructed SH irradiance E(N), 3=lightmap uv1 as colour. */
    "uniform int u_debug_mode;\n"
    "const float PI = 3.14159265359;\n"
    /* Irradiance from the baked SH lightmap in direction n (Ramamoorthi cosine\n"
     * lobe: A0=pi, A1=2pi/3, A2=pi/4). Matches lm_sh9_irradiance exactly. */
    "vec3 pbr_sh_irradiance(vec3 n){\n"
    "  float x=n.x, y=n.y, z=n.z;\n"
    "  float b0=0.282094792;\n"
    "  float b1=0.488602512*y, b2=0.488602512*z, b3=0.488602512*x;\n"
    "  float b4=1.092548431*x*y, b5=1.092548431*y*z, b6=0.315391565*(3.0*z*z-1.0),\n"
    "        b7=1.092548431*x*z, b8=0.546274215*(x*x-y*y);\n"
    "  vec3 E = 3.14159265*texture(u_sh0,v_uv1).rgb*b0;\n"
    "  E += 2.09439510*(texture(u_sh1,v_uv1).rgb*b1 + texture(u_sh2,v_uv1).rgb*b2 + texture(u_sh3,v_uv1).rgb*b3);\n"
    "  E += 0.78539816*(texture(u_sh4,v_uv1).rgb*b4 + texture(u_sh5,v_uv1).rgb*b5 + texture(u_sh6,v_uv1).rgb*b6 + texture(u_sh7,v_uv1).rgb*b7 + texture(u_sh8,v_uv1).rgb*b8);\n"
    "  return E;\n"
    "}\n"
    "float D_GGX(float NoH, float a){ float a2=a*a; float d=(NoH*NoH*(a2-1.0)+1.0); return a2/max(PI*d*d,1e-7); }\n"
    "float G_SchlickGGX(float NoX, float k){ return NoX/(NoX*(1.0-k)+k); }\n"
    "float G_Smith(float NoV, float NoL, float r){ float k=(r+1.0); k=k*k/8.0; return G_SchlickGGX(NoV,k)*G_SchlickGGX(NoL,k); }\n"
    "vec3 F_Schlick(float VoH, vec3 F0){ return F0 + (1.0-F0)*pow(clamp(1.0-VoH,0.0,1.0),5.0); }\n"
    /* Outgoing radiance for one light of unit colour arriving along L (includes\n"
     * the N.L cosine): Cook-Torrance specular + Lambert diffuse. */
    "vec3 pbr_light(vec3 N, vec3 V, vec3 L, vec3 albedo, float rough, float metal, vec3 F0){\n"
    "  float NoL = max(dot(N,L),0.0);\n"
    "  if(NoL<=0.0) return vec3(0.0);\n"
    "  vec3 H = normalize(V+L);\n"
    "  float NoV = max(dot(N,V),1e-4), NoH = max(dot(N,H),0.0), VoH = max(dot(V,H),0.0);\n"
    "  float D = D_GGX(NoH, rough*rough);\n"
    "  float G = G_Smith(NoV, NoL, rough);\n"
    "  vec3  F = F_Schlick(VoH, F0);\n"
    "  vec3 spec = (D*G)*F / max(4.0*NoV*NoL, 1e-4);\n"
    "  vec3 kd = (vec3(1.0)-F)*(1.0-metal);\n"
    "  return (kd*albedo/PI + spec) * NoL;\n"
    "}\n"
    /* Smooth inverse-square attenuation with a range window (matches lm_light). */
    "float pbr_atten(float dist, float range){\n"
    "  float w = clamp(1.0 - pow(dist/max(range,1e-3),4.0), 0.0, 1.0); w*=w;\n"
    "  return w / max(dist*dist, 1e-4);\n"
    "}\n"
    /* Contribution of one punctual light (type/pos/dir/colour/range/cone). */
    "vec3 pbr_accumulate(int ty, vec3 lpos, vec3 ldir, vec3 lcolor, float lrange,\n"
    "                    float lci, float lco, vec3 N, vec3 V, vec3 albedo,\n"
    "                    float rough, float metal, vec3 F0){\n"
    "  vec3 L; float atten = 1.0;\n"
    "  if(ty==1){ L = normalize(-ldir); }\n"
    "  else {\n"
    "    vec3 d = lpos - v_world_pos; float dist = length(d);\n"
    "    L = d / max(dist,1e-4); atten = pbr_atten(dist, lrange);\n"
    "    if(ty==2){ float c = dot(-L, normalize(ldir)); atten *= smoothstep(lco, lci, c); }\n"
    "  }\n"
    "  return pbr_light(N,V,L,albedo,rough,metal,F0) * lcolor * atten;\n"
    "}\n"
    /* Omnidirectional cube shadow for the one movable point light whose flat\n"
     * light-buffer index == u_shadow_light (-1 = none). The cube stores linear\n"
     * light->fragment distance / far; PCF-compare in 20 sample directions. */
    "uniform samplerCube u_shadow_cube;\n"
    "uniform int u_shadow_light;\n"
    "uniform float u_shadow_far;\n"
    "uniform float u_shadow_bias;\n"
    "const vec3 SC_OFFS[20] = vec3[](vec3(1,1,1),vec3(1,-1,1),vec3(-1,-1,1),vec3(-1,1,1),\n"
    "  vec3(1,1,-1),vec3(1,-1,-1),vec3(-1,-1,-1),vec3(-1,1,-1),vec3(1,1,0),vec3(1,-1,0),\n"
    "  vec3(-1,-1,0),vec3(-1,1,0),vec3(1,0,1),vec3(-1,0,1),vec3(1,0,-1),vec3(-1,0,-1),\n"
    "  vec3(0,1,1),vec3(0,-1,1),vec3(0,-1,-1),vec3(0,1,-1));\n"
    "float pbr_cube_shadow(vec3 lpos){\n"
    "  vec3 ftl = v_world_pos - lpos;\n"
    "  float cur = length(ftl);\n"
    "  if(cur >= u_shadow_far) return 1.0;\n"
    "  float radius = 0.015*cur + 0.01;\n"
    "  float lit = 0.0;\n"
    "  for(int i=0;i<20;++i){\n"
    "    float d = texture(u_shadow_cube, ftl + SC_OFFS[i]*radius).r * u_shadow_far;\n"
    "    lit += (cur - u_shadow_bias > d) ? 0.0 : 1.0;\n"
    "  }\n"
    "  return lit / 20.0;\n"
    "}\n"
    "void main() {\n"
    /* Material textures tile at u_uv_scale; the lightmap (v_uv1) is NOT scaled. */
    "  vec2 muv = v_uv0 * u_uv_scale;\n"
    "  vec3 albedo = u_tint;\n"
    "  if(u_has_albedo==1) albedo *= texture(u_albedo_map, muv).rgb;\n"
    "  float metal = u_metalness;\n"
    "  if(u_has_metallic==1) metal *= texture(u_metallic_map, muv).r;\n"
    "  metal = clamp(metal, 0.0, 1.0);\n"
    "  float rsample = (u_has_roughness==1) ? texture(u_roughness_map, muv).r : 1.0;\n"
    "  float rough = clamp(mix(u_roughness_min, u_roughness_max, rsample), 0.045, 1.0);\n"
    "  float ao = 1.0;\n"
    "  if(u_has_ao==1) ao = mix(1.0, texture(u_ao_map, muv).r, u_ao_strength);\n"
    "  vec3 N = normalize(v_normal);\n"
    "  if(u_has_normal==1){\n"
    "    vec3 tn = texture(u_normal_map, muv).xyz*2.0-1.0;\n"
    "    tn.xy *= u_normal_scale;\n"
    "    mat3 TBN = mat3(normalize(v_tangent), normalize(v_bitangent), N);\n"
    "    N = normalize(TBN * tn);\n"
    "  }\n"
    "  vec3 V = normalize(u_eye_pos - v_world_pos);\n"
    "  vec3 F0 = mix(vec3(0.08*u_specular_strength), albedo, metal);\n"
    /* Directional sun. */
    "  vec3 direct = pbr_light(N, V, normalize(u_sun_dir), albedo, rough, metal, F0) * u_sun_color;\n"
    "  if(u_clustered==1){\n"
    /* Forward+: find this fragment's cluster and shade only its lights. */
    "    int dimx=int(u_cluster_dims.x), dimy=int(u_cluster_dims.y), dimz=int(u_cluster_dims.z);\n"
    "    int tx = int(gl_FragCoord.x / u_screen.x * u_cluster_dims.x);\n"
    "    int ty = int(gl_FragCoord.y / u_screen.y * u_cluster_dims.y);\n"
    "    float vz = max(-v_view_z, u_cluster_near);\n"
    "    int sl = int(log(vz/u_cluster_near) / log(u_cluster_far/u_cluster_near) * u_cluster_dims.z);\n"
    "    tx = clamp(tx,0,dimx-1); ty = clamp(ty,0,dimy-1); sl = clamp(sl,0,dimz-1);\n"
    "    int cluster = (sl*dimy + ty)*dimx + tx;\n"
    "    int roff = texelFetch(u_cluster_offset, cluster).r;\n"
    "    int rcnt = texelFetch(u_cluster_count, cluster).r;\n"
    "    for(int i=0; i<rcnt; ++i){\n"
    "      int li = texelFetch(u_light_index, roff + i).r;\n"
    "      int b = li*4;\n"
    "      vec4 t0=texelFetch(u_light_data,b), t1=texelFetch(u_light_data,b+1),\n"
    "           t2=texelFetch(u_light_data,b+2), t3=texelFetch(u_light_data,b+3);\n"
    "      float sh = (li==u_shadow_light) ? pbr_cube_shadow(t0.yzw) : 1.0;\n"
    "      direct += sh * pbr_accumulate(int(t0.x), t0.yzw, t1.xyz, t2.xyz, t1.w, t2.w, t3.x,\n"
    "                               N,V,albedo,rough,metal,F0);\n"
    "    }\n"
    "  } else {\n"
    /* Direct uniform-array path (non-clustered). */
    "    for(int i=0; i<u_light_count && i<PBR_MAX_LIGHTS; ++i)\n"
    "      direct += pbr_accumulate(u_light_type[i], u_light_pos[i], u_light_dir[i],\n"
    "                               u_light_color[i], u_light_range[i], u_light_cos_inner[i],\n"
    "                               u_light_cos_outer[i], N,V,albedo,rough,metal,F0);\n"
    "  }\n"
    "  if(u_debug_mode==1){ frag=vec4(texture(u_sh0,v_uv1).rgb,1.0); return; }\n"
    "  if(u_debug_mode==2){ frag=vec4(max(pbr_sh_irradiance(N),vec3(0.0)),1.0); return; }\n"
    "  if(u_debug_mode==3){ frag=vec4(v_uv1,0.0,1.0); return; }\n"
    "  if(u_debug_mode==4){ frag=vec4(0.5+0.5*N,1.0); return; }\n"
    "  if(u_debug_mode==5){ frag=vec4(0.5+0.5*normalize(v_tangent),1.0); return; }\n"
    "  vec3 ambient;\n"
    "  if(u_sh_enabled==1){ vec3 E = max(pbr_sh_irradiance(N), vec3(0.0)); ambient = albedo*E*u_sh_scale/PI*ao; }\n"
    "  else { ambient = u_ambient*albedo*ao; }\n"
    "  vec3 color = direct + ambient;\n"
    /* Emissive self-shading: the surface shows its own emission (the actual\n"
     * emissive LIGHTING of the scene is baked into the lightmap). Driven by the\n"
     * emissive colour, modulated by the emissive map when present. */
    "  vec3 emissive = u_emissive_color * u_emissive_strength;\n"
    "  if(u_has_emissive==1) emissive *= texture(u_emissive_map,muv).rgb;\n"
    "  color += emissive;\n"
    "  color = color/(color+vec3(1.0));\n"
    "  color = pow(color, vec3(1.0/2.2));\n"
    "  frag = vec4(color,1.0);\n"
    "}\n";

const char *pbr_shader_vertex_source(void) { return PBR_VS; }
const char *pbr_shader_fragment_source(void) { return PBR_FS; }

shader_program_status_t pbr_shader_create(shader_program_t *out,
                                          const gl_loader_t *loader, char *log,
                                          size_t log_cap)
{
    return shader_program_create(out, loader, PBR_VS, PBR_FS, log, log_cap);
}
